x<-1:1000#给变量x赋值1-1000
y=tan(x)#y为x的正弦
z<-1/y#z为y的倒数
print(z)#输出z
x==z#比较x与z
identical(x,z)#比较x，z中数字是否相等
all.equal(x,z,tolerance=0)#容差设置为0
true_and_missin<-c(TRUE,NA)
false_and_missing<-c(FALSE,NA)
mixed<-c(TRUE,FALSE,NA)
any(true_and_missing)
any(false_and_missing)
any(mixed)
all(true_and_missin)
all(false_and_missing)
all(mixed)
hdgs<-sample(50:1000,100,replace=T)
sum(hdgs)
median(hdgs)
mean(hdgs)
var(hdgs)
dimaster<-atan(1000)
S<-pi*(dimaster/2)^2
P1X<-2
P1Y<-3
P2X<-13
P2Y<-22
L=sqrt((P1X-P2X)^2+(P1Y-P2Y)^2)
L

